spring.application.name=afes-backend

spring.datasource.url=jdbc:mysql://afes-db.mysql.database.azure.com:3306/afes_db?useSSL=true&requireSSL=false&serverTimezone=UTC

spring.datasource.username=admin123
spring.datasource.password=Hello123


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mqtt.broker.url=tcp://mosquitto:1883
mqtt.client.id=afes-backend-client
mqtt.username=Flame_Detection_System
mqtt.password=123
mqtt.topics=yolo_uno/sensors/flame,yolo_uno/sensors/smoke,yolo_uno/sensors/dht20
mqtt.control.topic=yolo_uno/control